# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .aggregate_field_expr_arg import AggregateFieldExprArg
from .aggregate_field_expr_func import AggregateFieldExprFunc


class AggregateFieldExpr(UniversalBaseModel):
    """
    Aggregate over unnested list elements, optionally targeting a struct field.

    When arg is None, the aggregate operates on the list elements directly
    (e.g., count-all, or mean/sum on a scalar numeric list).
    When arg is a FieldExpr, the struct field is extracted before aggregating.
    """

    func: AggregateFieldExprFunc = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    arg: typing.Optional[AggregateFieldExprArg] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
