# This file was auto-generated by Fern from our API Definition.

import typing

from .element_field_expr import ElementFieldExpr
from .mc_basal_body_temperature_field_expr import McBasalBodyTemperatureFieldExpr
from .mc_cervical_mucus_field_expr import McCervicalMucusFieldExpr
from .mc_contraceptive_field_expr import McContraceptiveFieldExpr
from .mc_detected_deviations_field_expr import McDetectedDeviationsFieldExpr
from .mc_home_pregnancy_test_field_expr import McHomePregnancyTestFieldExpr
from .mc_home_progesterone_test_field_expr import McHomeProgesteroneTestFieldExpr
from .mc_intermenstrual_bleeding_field_expr import McIntermenstrualBleedingFieldExpr
from .mc_menstrual_flow_field_expr import McMenstrualFlowFieldExpr
from .mc_ovulation_test_field_expr import McOvulationTestFieldExpr
from .mc_sexual_activity_field_expr import McSexualActivityFieldExpr

AggregateFieldExprArg = typing.Union[
    McMenstrualFlowFieldExpr,
    McCervicalMucusFieldExpr,
    McIntermenstrualBleedingFieldExpr,
    McContraceptiveFieldExpr,
    McDetectedDeviationsFieldExpr,
    McOvulationTestFieldExpr,
    McHomePregnancyTestFieldExpr,
    McHomeProgesteroneTestFieldExpr,
    McSexualActivityFieldExpr,
    McBasalBodyTemperatureFieldExpr,
    ElementFieldExpr,
]
