# This file was auto-generated by Fern from our API Definition.

import typing

AppointmentStatus = typing.Union[
    typing.Literal["confirmed", "pending", "in_progress", "completed", "cancelled"], typing.Any
]
