# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_facing_fall_changed_event_type import ClientFacingFallChangedEventType
from .grouped_fall import GroupedFall


class ClientFacingFallChanged(UniversalBaseModel):
    event_type: ClientFacingFallChangedEventType
    user_id: str
    client_user_id: str
    team_id: str
    data: GroupedFall

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
