# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingCaloriesActiveChangedEventType(str, enum.Enum):
    DAILY_DATA_CALORIES_ACTIVE_CREATED = "daily.data.calories_active.created"
    DAILY_DATA_CALORIES_ACTIVE_UPDATED = "daily.data.calories_active.updated"
    _UNKNOWN = "__CLIENTFACINGCALORIESACTIVECHANGEDEVENTTYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ClientFacingCaloriesActiveChangedEventType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        daily_data_calories_active_created: typing.Callable[[], T_Result],
        daily_data_calories_active_updated: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ClientFacingCaloriesActiveChangedEventType.DAILY_DATA_CALORIES_ACTIVE_CREATED:
            return daily_data_calories_active_created()
        if self is ClientFacingCaloriesActiveChangedEventType.DAILY_DATA_CALORIES_ACTIVE_UPDATED:
            return daily_data_calories_active_updated()
        return _unknown_member(self._value_)
