# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingBodyChangedEventType(str, enum.Enum):
    DAILY_DATA_BODY_CREATED = "daily.data.body.created"
    DAILY_DATA_BODY_UPDATED = "daily.data.body.updated"

    def visit(
        self,
        daily_data_body_created: typing.Callable[[], T_Result],
        daily_data_body_updated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClientFacingBodyChangedEventType.DAILY_DATA_BODY_CREATED:
            return daily_data_body_created()
        if self is ClientFacingBodyChangedEventType.DAILY_DATA_BODY_UPDATED:
            return daily_data_body_updated()
