# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingStandHourChangedEventType(str, enum.Enum):
    DAILY_DATA_STAND_HOUR_CREATED = "daily.data.stand_hour.created"
    DAILY_DATA_STAND_HOUR_UPDATED = "daily.data.stand_hour.updated"
    _UNKNOWN = "__CLIENTFACINGSTANDHOURCHANGEDEVENTTYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ClientFacingStandHourChangedEventType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        daily_data_stand_hour_created: typing.Callable[[], T_Result],
        daily_data_stand_hour_updated: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ClientFacingStandHourChangedEventType.DAILY_DATA_STAND_HOUR_CREATED:
            return daily_data_stand_hour_created()
        if self is ClientFacingStandHourChangedEventType.DAILY_DATA_STAND_HOUR_UPDATED:
            return daily_data_stand_hour_updated()
        return _unknown_member(self._value_)
