# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingBasalBodyTemperatureChangedEventType(str, enum.Enum):
    DAILY_DATA_BASAL_BODY_TEMPERATURE_CREATED = "daily.data.basal_body_temperature.created"
    DAILY_DATA_BASAL_BODY_TEMPERATURE_UPDATED = "daily.data.basal_body_temperature.updated"

    def visit(
        self,
        daily_data_basal_body_temperature_created: typing.Callable[[], T_Result],
        daily_data_basal_body_temperature_updated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClientFacingBasalBodyTemperatureChangedEventType.DAILY_DATA_BASAL_BODY_TEMPERATURE_CREATED:
            return daily_data_basal_body_temperature_created()
        if self is ClientFacingBasalBodyTemperatureChangedEventType.DAILY_DATA_BASAL_BODY_TEMPERATURE_UPDATED:
            return daily_data_basal_body_temperature_updated()
