# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_status import OrderStatus
from .order_status_detail import OrderStatusDetail


class ClientFacingOrderEvent(UniversalBaseModel):
    id: int
    created_at: dt.datetime
    status: OrderStatus
    status_detail: typing.Optional[OrderStatusDetail] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
