# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_facing_forced_expiratory_volume_1_changed_event_type import (
    ClientFacingForcedExpiratoryVolume1ChangedEventType,
)
from .vital_core_schemas_response_schemas_timeseries_client_facing_timeseries_group_client_facing_forced_expiratory_volume_1_sample import (
    VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedExpiratoryVolume1Sample,
)


class ClientFacingForcedExpiratoryVolume1Changed(UniversalBaseModel):
    event_type: ClientFacingForcedExpiratoryVolume1ChangedEventType
    user_id: str
    client_user_id: str
    team_id: str
    data: VitalCoreSchemasResponseSchemasTimeseriesClientFacingTimeseriesGroupClientFacingForcedExpiratoryVolume1Sample

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
