# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingSleepChangedEventType(str, enum.Enum):
    DAILY_DATA_SLEEP_CREATED = "daily.data.sleep.created"
    DAILY_DATA_SLEEP_UPDATED = "daily.data.sleep.updated"

    def visit(
        self,
        daily_data_sleep_created: typing.Callable[[], T_Result],
        daily_data_sleep_updated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClientFacingSleepChangedEventType.DAILY_DATA_SLEEP_CREATED:
            return daily_data_sleep_created()
        if self is ClientFacingSleepChangedEventType.DAILY_DATA_SLEEP_UPDATED:
            return daily_data_sleep_updated()
