# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingCaloriesActiveChangedEventType(str, enum.Enum):
    DAILY_DATA_CALORIES_ACTIVE_CREATED = "daily.data.calories_active.created"
    DAILY_DATA_CALORIES_ACTIVE_UPDATED = "daily.data.calories_active.updated"

    def visit(
        self,
        daily_data_calories_active_created: typing.Callable[[], T_Result],
        daily_data_calories_active_updated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClientFacingCaloriesActiveChangedEventType.DAILY_DATA_CALORIES_ACTIVE_CREATED:
            return daily_data_calories_active_created()
        if self is ClientFacingCaloriesActiveChangedEventType.DAILY_DATA_CALORIES_ACTIVE_UPDATED:
            return daily_data_calories_active_updated()
