# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_facing_sleep_apnea_alert_changed_event_type import ClientFacingSleepApneaAlertChangedEventType
from .grouped_sleep_apnea_alert import GroupedSleepApneaAlert


class ClientFacingSleepApneaAlertChanged(UniversalBaseModel):
    event_type: ClientFacingSleepApneaAlertChangedEventType
    user_id: str
    client_user_id: str
    team_id: str
    data: GroupedSleepApneaAlert

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
