# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingMealChangedEventType(str, enum.Enum):
    DAILY_DATA_MEAL_CREATED = "daily.data.meal.created"
    DAILY_DATA_MEAL_UPDATED = "daily.data.meal.updated"

    def visit(
        self,
        daily_data_meal_created: typing.Callable[[], T_Result],
        daily_data_meal_updated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClientFacingMealChangedEventType.DAILY_DATA_MEAL_CREATED:
            return daily_data_meal_created()
        if self is ClientFacingMealChangedEventType.DAILY_DATA_MEAL_UPDATED:
            return daily_data_meal_updated()
