# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClientFacingCholesterolChangedEventType(str, enum.Enum):
    DAILY_DATA_CHOLESTEROL_CREATED = "daily.data.cholesterol.created"
    DAILY_DATA_CHOLESTEROL_UPDATED = "daily.data.cholesterol.updated"
    _UNKNOWN = "__CLIENTFACINGCHOLESTEROLCHANGEDEVENTTYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ClientFacingCholesterolChangedEventType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        daily_data_cholesterol_created: typing.Callable[[], T_Result],
        daily_data_cholesterol_updated: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ClientFacingCholesterolChangedEventType.DAILY_DATA_CHOLESTEROL_CREATED:
            return daily_data_cholesterol_created()
        if self is ClientFacingCholesterolChangedEventType.DAILY_DATA_CHOLESTEROL_UPDATED:
            return daily_data_cholesterol_updated()
        return _unknown_member(self._value_)
