# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClientFacingWalkInTestOrder(UniversalBaseModel):
    """
    Schema for a walk-in test order in the client facing API.

    To be used as part of a ClientFacingOrder.
    """

    id: str = pydantic.Field()
    """
    The Vital walk-in test Order ID
    """

    created_at: dt.datetime
    updated_at: dt.datetime
    appointment_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
