# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .client_facing_connection_error_details_error_type import ClientFacingConnectionErrorDetailsErrorType
import pydantic
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ClientFacingConnectionErrorDetails(UniversalBaseModel):
    error_type: ClientFacingConnectionErrorDetailsErrorType = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    error_message: str
    errored_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
