# This file was auto-generated by Fern from our API Definition.

import typing

ContraceptiveEntryType = typing.Union[
    typing.Literal["unspecified", "implant", "injection", "iud", "intravaginal_ring", "oral", "patch"], typing.Any
]
