# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class DateTimeUnit(str, enum.Enum):
    MINUTE = "minute"
    HOUR = "hour"
    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"

    def visit(
        self,
        minute: typing.Callable[[], T_Result],
        hour: typing.Callable[[], T_Result],
        day: typing.Callable[[], T_Result],
        week: typing.Callable[[], T_Result],
        month: typing.Callable[[], T_Result],
        year: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is DateTimeUnit.MINUTE:
            return minute()
        if self is DateTimeUnit.HOUR:
            return hour()
        if self is DateTimeUnit.DAY:
            return day()
        if self is DateTimeUnit.WEEK:
            return week()
        if self is DateTimeUnit.MONTH:
            return month()
        if self is DateTimeUnit.YEAR:
            return year()
