# This file was auto-generated by Fern from our API Definition.

import typing

DelegatedFlowType = typing.Union[
    typing.Literal[
        "order_and_results_with_customer_physician_network",
        "order_with_vital_physician_network",
        "order_and_results_with_vital_physician_network",
    ],
    typing.Any,
]
