# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class DemoProviders(str, enum.Enum):
    APPLE_HEALTH_KIT = "apple_health_kit"
    FITBIT = "fitbit"
    FREESTYLE_LIBRE = "freestyle_libre"
    OURA = "oura"

    def visit(
        self,
        apple_health_kit: typing.Callable[[], T_Result],
        fitbit: typing.Callable[[], T_Result],
        freestyle_libre: typing.Callable[[], T_Result],
        oura: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is DemoProviders.APPLE_HEALTH_KIT:
            return apple_health_kit()
        if self is DemoProviders.FITBIT:
            return fitbit()
        if self is DemoProviders.FREESTYLE_LIBRE:
            return freestyle_libre()
        if self is DemoProviders.OURA:
            return oura()
