# This file was auto-generated by Fern from our API Definition.

import typing

EventDestinationPreferencesEnabledItem = typing.Union[
    typing.Literal["cloud_pubsub", "rabbitmq", "svix", "azure_amqp"], typing.Any
]
