# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .home_pregnancy_test_entry_test_result import HomePregnancyTestEntryTestResult
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class HomePregnancyTestEntry(UniversalBaseModel):
    date: str
    test_result: HomePregnancyTestEntryTestResult = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
