# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .add_on_order import AddOnOrder
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class OrderSetRequest(UniversalBaseModel):
    lab_test_ids: typing.Optional[typing.List[str]] = None
    add_on: typing.Optional[AddOnOrder] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
