# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_low_level_status import OrderLowLevelStatus
from .order_origin import OrderOrigin


class OrderSummary(UniversalBaseModel):
    """
    Lightweight order summary.
    """

    id: str
    origin: typing.Optional[OrderOrigin] = pydantic.Field(default=None)
    """
    ℹ️ This enum is non-exhaustive.
    """

    parent_id: typing.Optional[str] = None
    last_status: OrderLowLevelStatus = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    last_status_created_at: dt.datetime
    updated_at: dt.datetime
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
