# This file was auto-generated by Fern from our API Definition.

import typing

PasswordProviders = typing.Union[
    typing.Literal[
        "whoop",
        "renpho",
        "peloton",
        "zwift",
        "eight_sleep",
        "beurer_api",
        "dexcom",
        "hammerhead",
        "my_fitness_pal",
        "kardia",
        "abbott_libreview",
    ],
    typing.Any,
]
