# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .psc_area_info_details import PscAreaInfoDetails
import typing
from .billing import Billing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class PscAreaInfo(UniversalBaseModel):
    patient_service_centers: PscAreaInfoDetails
    supported_bill_types: typing.List[Billing]
    lab_id: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
