# This file was auto-generated by Fern from our API Definition.

import typing
from .sleep_selector import SleepSelector
from .activity_selector import ActivitySelector

QueryInstructionSelect = typing.Union[SleepSelector, ActivitySelector]
