# This file was auto-generated by Fern from our API Definition.

import typing

from .placeholder import Placeholder
from .unnest_expr import UnnestExpr

ScalarOutputSubqueryExprFrom = typing.Union[UnnestExpr, Placeholder]
