# This file was auto-generated by Fern from our API Definition.

import typing

from .aggregate_field_expr import AggregateFieldExpr
from .placeholder import Placeholder

ScalarOutputSubqueryExprSelect = typing.Union[AggregateFieldExpr, Placeholder]
