# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SessionPartitioningSession(str, enum.Enum):
    MENSTRUAL_CYCLE = "menstrual_cycle"
    WORKOUT = "workout"

    def visit(self, menstrual_cycle: typing.Callable[[], T_Result], workout: typing.Callable[[], T_Result]) -> T_Result:
        if self is SessionPartitioningSession.MENSTRUAL_CYCLE:
            return menstrual_cycle()
        if self is SessionPartitioningSession.WORKOUT:
            return workout()
