# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .interpretation import Interpretation
from .result_type import ResultType


class SimulationFlags(UniversalBaseModel):
    interpretation: typing.Optional[Interpretation] = None
    result_types: typing.Optional[typing.List[ResultType]] = None
    has_missing_results: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
