# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .historical_pull_status import HistoricalPullStatus
import typing
from .historical_pull_timeline import HistoricalPullTimeline
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class SingleHistoricalPullStatistics(UniversalBaseModel):
    status: HistoricalPullStatus
    range_start: typing.Optional[str] = None
    range_end: typing.Optional[str] = None
    timeline: HistoricalPullTimeline
    days_with_data: typing.Optional[int] = None
    release: str
    trace_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
