# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SleepCycleSourceType(str, enum.Enum):
    UNKNOWN = "unknown"
    PHONE = "phone"
    WATCH = "watch"
    APP = "app"
    MULTIPLE_SOURCES = "multiple_sources"
    FINGERPRICK = "fingerprick"
    CUFF = "cuff"
    MANUAL_SCAN = "manual_scan"
    AUTOMATIC = "automatic"
    SCALE = "scale"
    CHEST_STRAP = "chest_strap"
    RING = "ring"
    LAB = "lab"

    def visit(
        self,
        unknown: typing.Callable[[], T_Result],
        phone: typing.Callable[[], T_Result],
        watch: typing.Callable[[], T_Result],
        app: typing.Callable[[], T_Result],
        multiple_sources: typing.Callable[[], T_Result],
        fingerprick: typing.Callable[[], T_Result],
        cuff: typing.Callable[[], T_Result],
        manual_scan: typing.Callable[[], T_Result],
        automatic: typing.Callable[[], T_Result],
        scale: typing.Callable[[], T_Result],
        chest_strap: typing.Callable[[], T_Result],
        ring: typing.Callable[[], T_Result],
        lab: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is SleepCycleSourceType.UNKNOWN:
            return unknown()
        if self is SleepCycleSourceType.PHONE:
            return phone()
        if self is SleepCycleSourceType.WATCH:
            return watch()
        if self is SleepCycleSourceType.APP:
            return app()
        if self is SleepCycleSourceType.MULTIPLE_SOURCES:
            return multiple_sources()
        if self is SleepCycleSourceType.FINGERPRICK:
            return fingerprick()
        if self is SleepCycleSourceType.CUFF:
            return cuff()
        if self is SleepCycleSourceType.MANUAL_SCAN:
            return manual_scan()
        if self is SleepCycleSourceType.AUTOMATIC:
            return automatic()
        if self is SleepCycleSourceType.SCALE:
            return scale()
        if self is SleepCycleSourceType.CHEST_STRAP:
            return chest_strap()
        if self is SleepCycleSourceType.RING:
            return ring()
        if self is SleepCycleSourceType.LAB:
            return lab()
