# This file was auto-generated by Fern from our API Definition.

import typing

SleepSelectorSleep = typing.Union[
    typing.Literal[
        "session_start",
        "session_end",
        "state",
        "duration_second",
        "stage_asleep_second",
        "stage_awake_second",
        "stage_light_second",
        "stage_rem_second",
        "stage_deep_second",
        "stage_unknown_second",
        "latency_second",
        "heart_rate_minimum",
        "heart_rate_mean",
        "heart_rate_maximum",
        "heart_rate_dip",
        "efficiency",
        "hrv_mean_rmssd",
        "hrv_mean_sdnn",
        "skin_temperature_delta",
        "respiratory_rate",
        "score",
        "source_type",
        "source_provider",
        "source_app_id",
    ],
    typing.Any,
]
