# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.get_order_transaction_response import GetOrderTransactionResponse
from ..types.lab_results_raw import LabResultsRaw
from .raw_client import AsyncRawOrderTransactionClient, RawOrderTransactionClient


class OrderTransactionClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrderTransactionClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrderTransactionClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrderTransactionClient
        """
        return self._raw_client

    def get_transaction(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrderTransactionResponse:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrderTransactionResponse
            Successful Response

        Examples
        --------
        from vital import Vital

        client = Vital(
            api_key="YOUR_API_KEY",
        )
        client.order_transaction.get_transaction(
            transaction_id="transaction_id",
        )
        """
        _response = self._raw_client.get_transaction(transaction_id, request_options=request_options)
        return _response.data

    def get_transaction_result(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LabResultsRaw:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LabResultsRaw
            Successful Response

        Examples
        --------
        from vital import Vital

        client = Vital(
            api_key="YOUR_API_KEY",
        )
        client.order_transaction.get_transaction_result(
            transaction_id="transaction_id",
        )
        """
        _response = self._raw_client.get_transaction_result(transaction_id, request_options=request_options)
        return _response.data

    def get_transaction_result_pdf(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            PDF with results

        Examples
        --------
        from vital import Vital

        client = Vital(
            api_key="YOUR_API_KEY",
        )
        client.order_transaction.get_transaction_result_pdf(
            transaction_id="transaction_id",
        )
        """
        with self._raw_client.get_transaction_result_pdf(transaction_id, request_options=request_options) as r:
            yield from r.data


class AsyncOrderTransactionClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrderTransactionClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrderTransactionClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrderTransactionClient
        """
        return self._raw_client

    async def get_transaction(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrderTransactionResponse:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrderTransactionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from vital import AsyncVital

        client = AsyncVital(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.order_transaction.get_transaction(
                transaction_id="transaction_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_transaction(transaction_id, request_options=request_options)
        return _response.data

    async def get_transaction_result(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LabResultsRaw:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LabResultsRaw
            Successful Response

        Examples
        --------
        import asyncio

        from vital import AsyncVital

        client = AsyncVital(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.order_transaction.get_transaction_result(
                transaction_id="transaction_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_transaction_result(transaction_id, request_options=request_options)
        return _response.data

    async def get_transaction_result_pdf(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            PDF with results

        Examples
        --------
        import asyncio

        from vital import AsyncVital

        client = AsyncVital(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.order_transaction.get_transaction_result_pdf(
                transaction_id="transaction_id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.get_transaction_result_pdf(transaction_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
